### ISSUE TITLE
Support for Visual Studio Build Tools?

### ISSUE THREAD

**Issue by likemike91** [kzu/dotnet-vs#44]
Is it planned to support the Visual Studio Build Tools as well?
This would allow us to automatically keep our Build Servers (with only Build Tools installed) updated when running `vs update` via a Scheduled Task.

**Comment by kzu** [comment]
Very good question. Could you point us to some info on how automated installation of that SKU can be done? 

Thanks!

**Comment by likemike91** [comment]
I would say some information could be derived from the Chocolatey package which allows installation of the Visual Studio Build Tools as well:
https://github.com/jberezanski/ChocolateyPackages/tree/master/visualstudio2019buildtools

Respectively the VS Installation Module which provides helpers for that task:
https://github.com/jberezanski/ChocolateyPackages/tree/master/chocolatey-visualstudio.extension/extensions

**Comment by kzu** [comment]
ok, found what I was looking for:

https://github.com/jberezanski/ChocolateyPackages/blob/master/visualstudio2019buildtools/tools/ChocolateyInstall.ps1#L4

> https://aka.ms/vs/16/release/vs_buildtools.exe

Installing it seems like it would be relatively easy to do (maybe `vs install build`?). But investigating how to do the updating seems more involved.

If you could come up with a PR, I'd be glad to review and merge it.

Thanks!

**Comment by likemike91** [comment]
@kzu I created a PR for it. Please let me know if something else needs to be changed. ;)
