### ISSUE TITLE
Make changing default version of VS explicit

### ISSUE THREAD

**Issue by BretJohnson** [kzu/dotnet-vs#5]
From Slack comment:

> Also, I think I'd prefer if the default didn't change when running an alternate version.
> That way, one can have a default version of VS used for most solutions (e.g. stable) and switch to an alternate version on an exception basis, w/o changing the default.
> To achieve that, you could have say a `--setDefault` option, along with the others, that updates the default when VS is launched.
> Also, optionally - this is more of a nice to have I think - you could store the default in the registry as the default program associated with .sln files.
> That way, the command line and File Explorer are in sync with the "default" version of VS, reading/writing the same setting.

As vswhere uses mixed case for option names (`-requiresAny`) could stick with that convention for `--setDefault`. And say have a `--clearDefault` option to remove the default. Or go with the mono.options convention of `default+` and `default-` to turn it on/off.

**Comment by kzu** [comment]
I like `--default+` and `--default-` :+1:
